### ISSUE TITLE
rds添加账号失败 InvalidDBDescription.Malformed : The specified parameter "DBDescription" is not valid

### ISSUE THREAD

**Issue by wikipurse** [wyzxxz/aksk_tool#12]
rds添加账号失败 InvalidDBDescription.Malformed : The specified parameter "DBDescription" is not valid

是不是阿里云的sdk 要更新？

**Comment by wyzxxz** [comment]
参数移除了，你下载下新的再试试

**Comment by wikipurse** [comment]
感谢大佬的及时更新已经可以了谢谢
