### ISSUE TITLE
工具没办法用，好像没上传对

### ISSUE THREAD

**Issue by w2n1ck** [wyzxxz/aksk_tool#2]
https://xz.aliyun.com/forum/upload/affix/aksk_tool.zip.zip  这个工具里面解压出来的是个html文件

$ file aksk_tool
aksk_tool: HTML document text, ASCII text, with very long lines

$ cat aksk_tool| more
<html><script>
var arg1='8B6466953896E450754EAAED129891358C104D05';
var _0x4818=['\x63\x73\x4b\x48\x77\x71\x4d\x49','\x5a\x73\x4b\x4a\x77\x72\x38\x56\x65\x41\x73\x79','\x55\x63\x4b\x69\x4e\x38\x4f\x2f\x77\x70\x6c\x77\x4d\x41\x3d\x3d',

**Comment by wyzxxz** [comment]
文件size: 31.5 MB，请确认下是否下载完成,，建议 unzip aksk_tool.zip.zip，然后 cd aksk_tool , 再 java -jar aksk_tool.jar
